server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/linktic_db
    username: app_user
    password: changeme
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

security:
  api-key: ${SECURITY_API_KEY:local-dev-key}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
