server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Proxy al product-service — rewrite elimina el prefijo /api/products
    location /api/products {
        rewrite ^/api/products(/?.*)$ /api/v1/products$1 break;
        proxy_pass http://product-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy al inventory-service — rewrite elimina el prefijo /api/inventory
    location /api/inventory {
        rewrite ^/api/inventory(/?.*)$ /api/v1/inventory$1 break;
        proxy_pass http://inventory-service:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # SPA fallback — todas las rutas van al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
