server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Proxy al product-service
    location /api/products/ {
        proxy_pass http://product-service:8080/api/v1/products/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy al inventory-service
    location /api/inventory/ {
        proxy_pass http://inventory-service:8081/api/v1/inventory/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # SPA fallback — todas las rutas van al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
